---
title: "My Cool Fisheries Analysis"
author: "Julia Large"
date: "1/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(paletteer)

us_landings <- read_csv(here("data/noaa_landings.csv"),
                        na = "no data") # this replaces all "no data" with normal N/A missing values

```

### Cleaning the data

```{r}

salmon_clean <- us_landings %>% 
  clean_names() %>% 
  mutate(afs_name = str_to_lower(afs_name)) %>% 
  mutate(dollars_num = parse_number(dollars_usd)) %>% 
  filter(str_detect(afs_name,
                    pattern = "salmon")) %>% 
  separate(afs_name,
           into = c("salmon_group", "subgroup"),
           sep = ", ") %>% 
  drop_na(dollars_num)

```

### Annual total value by salmon subgroup

```{r}

salmon_us_annual <- salmon_clean %>% 
  group_by(year, subgroup) %>% 
  summarize(tot_value = sum(dollars_num))
# to remove N/A values at this stage, then add 'na.rm = TRUE' : summarize(tot_value = sum(dollars_num, na.rm = TRUE))

```

### Create line graph

```{r}

ggplot(salmon_us_annual,
       aes(x = year, y = tot_value)) +
  geom_line(aes(color = subgroup)) +
  theme_light() +
  labs(x = "Year", y = "US Salmon Value", title = "My Awesome Graph") + # defines axis labels and titles
  scale_color_paletteer_d("calecopal::figmtn") # use "View(palettes_d_names)" in the console to view all the available pallettes

```




